### ISSUE TITLE
运行一堆报错，确定测试过？

### ISSUE THREAD

**Issue by bilinxing** [trueleaf/moyu-server#3]

**Comment by wildsell** [comment]
方便提供您的错误信息吗

**Comment by bilinxing** [comment]
/root/workspace/moyu/node_modules/electron/index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (/root/workspace/moyu/node_modules/electron/index.js:14:11)
    at Object.<anonymous> (/root/workspace/moyu/node_modules/electron/index.js:18:18)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/root/workspace/moyu/node_modules/vue-cli-plugin-electron-builder/lib/testWithSpectron.js:2:22)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)

Node.js v17.0.1

**Comment by wildsell** [comment]
国内环境安装electron通常不太稳定
可以尝试：
1. npm install  --registry=https://registry.npm.taobao.org --legacy-peer-deps (使用淘宝源)
2. yarn (使用yarn来安装)
3. 尝试使用cnpm来安装
3. 尝试降低node版本，例如 12~14然后重新尝试前面两步

**Comment by bilinxing** [comment]
换成node 14 可以了。 不过，我在导入文档的时候，报413错。我本地部署的，看请求接口居然是: https://online.jobtool.cn/api/project/import/moyu

**Comment by bilinxing** [comment]
虽然做了很多功能。但是部署文档，使用文档都很不完善，各种细节比如title还是vue，始终给人感觉是个demo，不敢用于生产的，这样很难推广起来的。

**Comment by wildsell** [comment]
> 换成node 14 可以了。 不过，我在导入文档的时候，报413错。我本地部署的，看请求接口居然是: https://online.jobtool.cn/api/project/import/moyu

为了方便用户仅部署客户端进行开发体验，默认我们将线上地址作为用户默认请求地址，你可以修改如图代码替换为本地地址。
![image](https://user-images.githubusercontent.com/30032830/139661935-b77984a8-875e-40f4-91aa-e89099def82f.png)

**Comment by wildsell** [comment]
> 虽然做了很多功能。但是部署文档，使用文档都很不完善，各种细节比如title还是vue，始终给人感觉是个demo，不敢用于生产的，这样很难推广起来的。

非常感谢您的反馈，我们正在加紧完善文档和相关测试细节，目前发布最新版本为0.8.0版本，我们会尽力在2022年之前发布第一个稳定版本。当前版本会在一些细节方面存在bug，但不影响基础流程使用，非常感谢您的体验，我们会尽快完善反馈的bug。

**Comment by FleyX** [comment]
好奇目前是你 @shuxiaokai3 一个人开发维护还是有一整个商业团队

**Comment by wildsell** [comment]
> 好奇目前是你 @shuxiaokai3 一个人开发维护还是有一整个商业团队

目前是一个人在开发维护！
